### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-DuilioAquino10#1]
[INFOGRAFIA.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-DuilioAquino10/files/8566545/INFOGRAFIA.pdf)

**Comment by Abraham890** [comment]
calificación: 20 puntos

**Comment by josealfredo79** [comment]
Falta la información de donde se obtuvo esta información

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
